### ISSUE TITLE
Design considerations for a new SDK

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/formsg-ruby-sdk#1]
During the development of https://github.com/opengovsg/formsg-javascript-sdk, there were design missteps that in hindsight would have been better to cater for at the start.

## SDK initialisation

```javascript
// Defaults to using FormSG's production public key
const formsg = require('@opengovsg/formsg-sdk')()

// Uses FormSG's staging public key
const formsg = require('@opengovsg/formsg-sdk')({
  mode: 'staging',
})
```

For ease of usage, the JavaScript SDK allowed developers to set the `mode` of the SDK. This required the SDK to hard-code the FormSG public keys that were being used. Applications would break if FormSG had a need to rotate the keys, or if integrating against other environments.

A more flexible posture would be to initialise by passing the public key explicitly:

```javascript
const formsg = require('@opengovsg/formsg-sdk')({
  publicKey: `rjv41kYqZwcbe3r6ymMEEKQ+Vd+DPuogN+Gzq3lP2Og=`,
})
```

## Supporting attachments in the future

At present, the decrypt step is a synchronous function that executes on the main thread:

```javascript
const submission = formsg.crypto.decrypt(formSecretKey, req.body.data)
```

FormSG webhooks do not support attachments at present because we do not think it is a good idea to directly transmit large blobs over the network. Instead, current discussions lean towards the FormSG server sending S3 pre-signed URLs for each attachment instead, and have the receiving system download attachments from S3 and decrypting that instead. This would require either changing the function signature to `async` (which is backward-incompatible) or introducing a new function.

**Comment by miccheng** [comment]
Thank you!

**Comment by liangyuanruo** [comment]
Happy to! I've filed an [issue](https://github.com/opengovsg/formsg-javascript-sdk/issues/46) to fix this with the JavaScript SDK

**Comment by miccheng** [comment]
This SDK lets users set the public key to use.

Here's the usage in the sample code: https://github.com/opengovsg/formsg-ruby-sdk/blob/main/sample_app/app.rb#L12
